services:
  db:
    image: mysql
    restart: always
    volumes:
      - ./src/dbdata/:/var/lib/mysql/
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_DATABASE: qortex_test
    ports:
      - 8111:3306
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci 
    #--skip-grant-tables
    container_name: qortex_db
# Сервис для phpmyadmin (опционально)
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    links:
      - db
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: 
    ports:
      - '8080:80'
    depends_on:
      - db    
  
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src/apache/:/etc/apache2/sites-available/
      - ./src/my-qortex-test/:/var/www/html/my-qortex-test/
    depends_on:
      - db
    container_name: qortex-app
    ports:
      - "8000:80"